### ISSUE TITLE
Modules Settings, Permissions stack and cause hidden items and scrolling

### ISSUE THREAD

**Issue by jeremy-farrance** [Accuraty/AccuTheme-fork#7]
The dnn-reset.scss makes all dnnFormItems display: block. One fringe case with a side effect is in Module Settings, Permissions. 

[This video demos the problem](https://accuraty-my.sharepoint.com/:v:/p/jfarrance/EYRvd3D5FdRDn68XHhbi6bABb7uuFJgxzjbuBLSBr0yY4A?e=dWbeNh).

Confuses the heck out of new users.

**Comment by jeremy-farrance** [comment]
Proposed fix, add this to the end of styles/theme/base/_dnn-reset.scss

```
//## DNN Module Settings, Permissions

.dnnPermissionsGrid {

  .dnnFormItem {

    .leftGroup, .rightGroup {
      label, select, a {
        display: inline-block;
      }
      a {
        padding: 0.25rem;
      }
    }

  }
}
```
Results should look like this:
![image](https://user-images.githubusercontent.com/653301/101190222-b1cebe80-361d-11eb-9c19-abc123275820.png)

**Comment by chrismlusk** [comment]
Good catch. That is coming from [this `@extend` rule](https://github.com/chrismlusk/accuraty-templates/blob/master/Portals/_default/Skins/CLIENT_CODE/src/styles/theme/base/_dnn-reset.scss#L284), so the simplest fix is to override the display with `display: initial`. I'll update.
